language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
sudo: false
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - bash <(curl -s https://codecov.io/bash)
